install.packages("ggmap")
install.packages("maptools")
install.packages("rgeos")
install.packages("readr")
install.packages("rgdal")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages(c("maps", "mapdata"))
library(ggmap)
library(maptools)
library(rgeos)
library(readr)
library(rgdal)
library(ggplot2)
library(tidyverse)
library(maps)
library(mapdata)
X=map_data("world")
view(X)
mapdata <- left_join(mapdata, country_wise_latest, by="region")
View(mapdata)
map1= ggplot(x.aes(x=long,y=lat,group=group))+geom_polygon(aes(fill=New cases),color="black")
plot(map1)
map2= map1+scale_fill_gradient(name="New cases",low="yellow",high = "red",na.value = "grey50")+theme(rect = element_blank())
plot(map2)
map2= map1+scale_fill_gradient(name="New cases",low="yellow",high = "red",na.value = "grey50")+theme(rect = element_blank().axis.text.x=element_blank().axis.text.y=element_blank())
plot(map2)


